name: generate-ecommerce-incident-report

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  generate-report:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        continue-on-error: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
        continue-on-error: true

      - name: Run Unit Tests
        run: |
          python tests/test_incident_processor.py
        continue-on-error: true
          
      - name: Run Incident Processor code
        run: |
          python incident_processor.py
        continue-on-error: true

      - name: Generate HTML Report
        run: |
          python generate_html_report.py
        continue-on-error: true
          
      - name: Publish test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results 
          path: ./test_results/
        continue-on-error: true
          
      - name: Slack Alert
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            📊 *E-Commerce Incidents Report*. Refer attached Url.
            Report_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        continue-on-error: true
