

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Report
        run: |
          echo "E-Commerce Incidents Report - $(date)" > report.txt
          
      - name: Upload HTML Reports as Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          name: Automation-Tests-html-reports
          path: ./test_results/
          
      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            📊 *E-Commerce Incidents Report*. Refer attached Url.
            Report_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      
          
     
